<a href="https://colab.research.google.com/github/mtairowodza/munyt/blob/colab/All_languages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Set-up for sql
%load_ext sql
%sql sqlite://
import pandas as pd
pd.DataFrame.iteritems = pd.DataFrame.items

In [3]:
#set up to allow magic command for R
%load_ext rpy2.ipython

In [4]:
#setup tp allow for interchange of datasets between pd and R

from rpy2.robjects import r, pandas2ri

In [5]:
pandas2ri.activate()

In [1]:
from google.colab import files
up=files.upload()

Saving nobel.csv to nobel.csv

In [15]:
import io
df2 = pd.read_csv(io.BytesIO(up['nobel.csv']))

In [20]:
%%R
library('dplyr')

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:
Attaching package: ‘dplyr’


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [16]:
# Create database tables from CSV files

with open('nobel.csv') as f: nobel = pd.read_csv('nobel.csv', encoding='unicode_escape', index_col=0)
%sql drop table if exists nobel;
%sql --persist nobel

 * sqlite://
Done.
 * sqlite://

'Persisted nobel'

In [18]:
from rpy2.robjects import r, pandas2ri
pandas2ri.activate()
rdf = pandas2ri.py2rpy(df2)
r.assign('rdf', df2)

,Year,Category,Prize,Motivation,Prize Share,Laureate ID,Laureate Type,Full Name,Birth Date,Birth City,Birth Country,Sex,Organization Name,Organization City,Organization Country,Death Date,Death City,Death Country
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,None,None,None,1907-09-07,Châtenay,France
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany
3,1901,Peace,The Nobel Peace Prize 1901,None,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,None,None,None,1910-10-30,Heiden,Switzerland
4,1901,Peace,The Nobel Peace Prize 1901,None,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,None,None,None,1912-06-12,Paris,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2016,Medicine,The Nobel Prize in Physiology or Medicine 2016,"""for his discoveries of mechanisms for autophagy""",1/1,927,Individual,Yoshinori Ohsumi,1945-02-09,Fukuoka,Japan,Male,Tokyo Institute of Technology,Tokyo,Japan,None,None,None
965,2016,Peace,The Nobel Peace Prize 2016,"""for his resolute efforts to bring the country...",1/1,934,Individual,Juan Manuel Santos,1951-08-10,Bogotá,Colombia,Male,None,None,None,None,None,None
966,2016,Physics,The Nobel Prize in Physics 2016,"""for theoretical discoveries of topological ph...",1/2,928,Individual,David J. Thouless,1934-09-21,Bearsden,United Kingdom,Male,University of Washington,"Seattle, WA",United States of America,None,None,None
967,2016,Physics,The Nobel Prize in Physics 2016,"""for theoretical discoveries of topological ph...",1/4,929,Individual,F. Duncan M. Haldane,1951-09-14,London,United Kingdom,Male,Princeton University,"Princeton, NJ",United States of America,None,None,None
968,2016,Physics,The Nobel Prize in Physics 2016,"""for theoretical discoveries of topological ph...",1/4,930,Individual,J. Michael Kosterlitz,1943-06-22,Aberdeen,United Kingdom,Male,Brown University,"Providence, RI",United States of America,None,None,None

In [10]:
%%R

head(rdf, 10)

  Year   Category                                          Prize
0 1901  Chemistry              The Nobel Prize in Chemistry 1901
1 1901 Literature             The Nobel Prize in Literature 1901
2 1901   Medicine The Nobel Prize in Physiology or Medicine 1901
3 1901      Peace                     The Nobel Peace Prize 1901
4 1901      Peace                     The Nobel Peace Prize 1901
5 1901    Physics                The Nobel Prize in Physics 1901
6 1902  Chemistry              The Nobel Prize in Chemistry 1902
7 1902 Literature             The Nobel Prize in Literature 1902
8 1902   Medicine The Nobel Prize in Physiology or Medicine 1902
9 1902      Peace                     The Nobel Peace Prize 1902
                                                                                                                                                                                                                                          Motivation
0                                                                                                 "in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions"
1                                                                "in special recognition of his poetic composition, which gives evidence of lofty idealism, artistic perfection and a rare combination of the qualities of both heart and intellect"
2 "for his work on serum therapy, especially its application against diphtheria, by which he has opened a new road in the domain of medical science and thereby placed in the hands of the physician a victorious weapon against illness and deaths"
3                                                                                                                                                                                                                                               <NA>
4                                                                                                                                                                                                                                               <NA>
5                                                                                                                "in recognition of the extraordinary services he has rendered by the discovery of the remarkable rays subsequently named after him"
6                                                                                                                                           "in recognition of the extraordinary services he has rendered by his work on sugar and purine syntheses"
7                                                                                                             "the greatest living master of the art of historical writing, with special reference to his monumental work, <I>A history of Rome</I>"
8                                                                "for his work on malaria, by which he has shown how it enters the organism and thereby has laid the foundation for successful research on this disease and methods of combating it"
9                                                                                                                                                                                                                                               <NA>
  Prize Share Laureate ID Laureate Type                          Full Name
0         1/1         160    Individual       Jacobus Henricus van 't Hoff
1         1/1         569    Individual                    Sully Prudhomme
2         1/1         293    Individual             Emil Adolf von Behring
3         1/2         462    Individual                  Jean Henry Dunant
4         1/2         463    Individual                     Frédéric Passy
5         1/1           1    Individual             Wilhelm Conrad Röntgen
6         1/1         161    Individual               Hermann Emil Fischer
7         1/1         571    Individual Christian Matthias Theodor Mommsen
8         1/1         294    Individual                        Ronald Ross
9         1/2         464    Individual                      Élie Ducommun
  Birth Date         Birth City       Birth Country  Sex  Organization Name
0 1852-08-30          Rotterdam         Netherlands Male  Berlin University
1 1839-03-16              Paris              France Male               <NA>
2 1854-03-15  Hansdorf (Lawice)    Prussia (Poland) Male Marburg University
3 1828-05-08             Geneva         Switzerland Male               <NA>
4 1822-05-20              Paris              France Male               <NA>
5 1845-03-27 Lennep (Remscheid)   Prussia (Germany) Male  Munich University
6 1852-10-09         Euskirchen   Prussia (Germany) Male  Berlin University
7 1817-11-30            Garding Schleswig (Germany) Male               <NA>
8 1857-05-13             Almora               India Male University College
9 1833-02-19             Geneva         Switzerland Male               <NA>
  Organization City Organization Country Death Date     Death City
0            Berlin              Germany 1911-03-01         Berlin
1              <NA>                 <NA> 1907-09-07       Châtenay
2           Marburg              Germany 1917-03-31        Marburg
3              <NA>                 <NA> 1910-10-30         Heiden
4              <NA>                 <NA> 1912-06-12          Paris
5            Munich              Germany 1923-02-10         Munich
6            Berlin              Germany 1919-07-15         Berlin
7              <NA>                 <NA> 1903-11-01 Charlottenburg
8         Liverpool       United Kingdom 1932-09-16   Putney Heath
9              <NA>                 <NA> 1906-12-07           Bern
   Death Country
0        Germany
1         France
2        Germany
3    Switzerland
4         France
5        Germany
6        Germany
7        Germany
8 United Kingdom
9    Switzerland

In [23]:
%%R
fd <- filter(rdf, `Birth Country` == 'United Kingdom')
fd

    Year   Category                                                 Prize
16  1903      Peace                            The Nobel Peace Prize 1903
25  1904    Physics                       The Nobel Prize in Physics 1904
36  1906    Physics                       The Nobel Prize in Physics 1906
85  1915    Physics                       The Nobel Prize in Physics 1915
91  1917    Physics                       The Nobel Prize in Physics 1917
103 1921  Chemistry                     The Nobel Prize in Chemistry 1921
108 1922  Chemistry                     The Nobel Prize in Chemistry 1922
110 1922   Medicine        The Nobel Prize in Physiology or Medicine 1922
124 1925      Peace                            The Nobel Peace Prize 1925
144 1928    Physics                       The Nobel Prize in Physics 1928
145 1929  Chemistry                     The Nobel Prize in Chemistry 1929
149 1929   Medicine        The Nobel Prize in Physiology or Medicine 1929
166 1932 Literature                    The Nobel Prize in Literature 1932
167 1932   Medicine        The Nobel Prize in Physiology or Medicine 1932
168 1932   Medicine        The Nobel Prize in Physiology or Medicine 1932
172 1933      Peace                            The Nobel Peace Prize 1933
174 1933    Physics                       The Nobel Prize in Physics 1933
186 1935    Physics                       The Nobel Prize in Physics 1935
190 1936   Medicine        The Nobel Prize in Physiology or Medicine 1936
195 1937  Chemistry                     The Nobel Prize in Chemistry 1937
199 1937      Peace                            The Nobel Peace Prize 1937
201 1937    Physics                       The Nobel Prize in Physics 1937
239 1947  Chemistry                     The Nobel Prize in Chemistry 1947
246 1947    Physics                       The Nobel Prize in Physics 1947
250 1948    Physics                       The Nobel Prize in Physics 1948
261 1950 Literature                    The Nobel Prize in Literature 1950
266 1950    Physics                       The Nobel Prize in Physics 1950
272 1951    Physics                       The Nobel Prize in Physics 1951
274 1952  Chemistry                     The Nobel Prize in Chemistry 1952
275 1952  Chemistry                     The Nobel Prize in Chemistry 1952
283 1953 Literature                    The Nobel Prize in Literature 1953
304 1956  Chemistry                     The Nobel Prize in Chemistry 1956
311 1956    Physics                       The Nobel Prize in Physics 1956
320 1958  Chemistry                     The Nobel Prize in Chemistry 1958
335 1959      Peace                            The Nobel Peace Prize 1959
352 1962  Chemistry                     The Nobel Prize in Chemistry 1962
354 1962   Medicine        The Nobel Prize in Physiology or Medicine 1962
363 1963   Medicine        The Nobel Prize in Physiology or Medicine 1963
364 1963   Medicine        The Nobel Prize in Physiology or Medicine 1963
394 1967  Chemistry                     The Nobel Prize in Chemistry 1967
395 1967  Chemistry                     The Nobel Prize in Chemistry 1967
408 1969  Chemistry                     The Nobel Prize in Chemistry 1969
436 1972  Economics The Sveriges Riksbank Prize in Economic Sciences 1972
440 1972   Medicine        The Nobel Prize in Physiology or Medicine 1972
445 1973  Chemistry                     The Nobel Prize in Chemistry 1973
447 1973 Literature                    The Nobel Prize in Literature 1973
455 1973    Physics                       The Nobel Prize in Physics 1973
462 1974   Medicine        The Nobel Prize in Physiology or Medicine 1974
463 1974   Medicine        The Nobel Prize in Physiology or Medicine 1974
467 1974    Physics                       The Nobel Prize in Physics 1974
468 1974    Physics                       The Nobel Prize in Physics 1974
493 1977  Economics The Sveriges Riksbank Prize in Economic Sciences 1977
500 1977    Physics                       The Nobel Prize in Physics 1977
502 1978  Chemistry                     The Nobel Prize in Chemistry 1978
513 1979  Chemistry                     The Nobel Prize in Chemistry 1979
519 1979   Medicine        The Nobel Prize in Physiology or Medicine 1979
525 1980  Chemistry                     The Nobel Prize in Chemistry 1980
552 1982   Medicine        The Nobel Prize in Physiology or Medicine 1982
558 1983 Literature                    The Nobel Prize in Literature 1983
564 1984  Economics The Sveriges Riksbank Prize in Economic Sciences 1984
566 1984   Medicine        The Nobel Prize in Physiology or Medicine 1984
636 1991  Economics The Sveriges Riksbank Prize in Economic Sciences 1991
651 1993  Chemistry                     The Nobel Prize in Chemistry 1993
655 1993   Medicine        The Nobel Prize in Physiology or Medicine 1993
686 1996  Chemistry                     The Nobel Prize in Chemistry 1996
699 1997  Chemistry                     The Nobel Prize in Chemistry 1997
712 1998  Chemistry                     The Nobel Prize in Chemistry 1998
752 2001   Medicine        The Nobel Prize in Physiology or Medicine 2001
753 2001   Medicine        The Nobel Prize in Physiology or Medicine 2001
768 2002   Medicine        The Nobel Prize in Physiology or Medicine 2002
777 2003  Economics The Sveriges Riksbank Prize in Economic Sciences 2003
780 2003   Medicine        The Nobel Prize in Physiology or Medicine 2003
784 2003    Physics                       The Nobel Prize in Physics 2003
804 2005 Literature                    The Nobel Prize in Literature 2005
831 2007   Medicine        The Nobel Prize in Physiology or Medicine 2007
832 2007   Medicine        The Nobel Prize in Physiology or Medicine 2007
863 2009   Medicine        The Nobel Prize in Physiology or Medicine 2009
864 2009   Medicine        The Nobel Prize in Physiology or Medicine 2009
865 2009   Medicine        The Nobel Prize in Physiology or Medicine 2009
879 2010   Medicine        The Nobel Prize in Physiology or Medicine 2010
906 2012   Medicine        The Nobel Prize in Physiology or Medicine 2012
929 2013    Physics                       The Nobel Prize in Physics 2013
950 2015  Economics The Sveriges Riksbank Prize in Economic Sciences 2015
959 2016  Chemistry                     The Nobel Prize in Chemistry 2016
961 2016  Economics The Sveriges Riksbank Prize in Economic Sciences 2016
966 2016    Physics                       The Nobel Prize in Physics 2016
967 2016    Physics                       The Nobel Prize in Physics 2016
968 2016    Physics                       The Nobel Prize in Physics 2016
                                                                                                                                                                                                                                                                                           Motivation
16                                                                                                                                                                                                                                                                                               <NA>
25                                                                                                                                                              "for his investigations of the densities of the most important gases and for his discovery of argon in connection with these studies"
36                                                                                                                                                                  "in recognition of the great merits of his theoretical and experimental investigations on the conduction of electricity by gases"
85                                                                                                                                                                                                                       "for their services in the analysis of crystal structure by means of X-rays"
91                                                                                                                                                                                                                   "for his discovery of the characteristic R&ouml;ntgen radiation of the elements"
103                                                                                                                                                "for his contributions to our knowledge of the chemistry of radioactive substances, and his investigations into the origin and nature of isotopes"
108                                                                                                                              "for his discovery, by means of his mass spectrograph, of isotopes, in a large number of non-radioactive elements, and for his enunciation of the whole-number rule"
110                                                                                                                                                                                                                              "for his discovery relating to the production of heat in the muscle"
124                                                                                                                                                                                                                                                                                              <NA>
144                                                                                                                                                                                           "for his work on the thermionic phenomenon and especially for the discovery of the law named after him"
145                                                                                                                                                                                                                  "for their investigations on the fermentation of sugar and fermentative enzymes"
149                                                                                                                                                                                                                                            "for his discovery of the growth-stimulating vitamins"
166                                                                                                                                                                                                  "for his distinguished art of narration which takes its highest form in <I>The Forsyte Saga</I>"
167                                                                                                                                                                                                                                        "for their discoveries regarding the functions of neurons"
168                                                                                                                                                                                                                                        "for their discoveries regarding the functions of neurons"
172                                                                                                                                                                                                                                                                                              <NA>
174                                                                                                                                                                                                                                      "for the discovery of new productive forms of atomic theory"
186                                                                                                                                                                                                                                                                "for the discovery of the neutron"
190                                                                                                                                                                                                                       "for their discoveries relating to chemical transmission of nerve impulses"
195                                                                                                                                                                                                                                           "for his investigations on carbohydrates and vitamin C"
199                                                                                                                                                                                                                                                                                              <NA>
201                                                                                                                                                                                                                    "for their experimental discovery of the diffraction of electrons by crystals"
239                                                                                                                                                                                                     "for his investigations on plant products of biological importance, especially the alkaloids"
246                                                                                                                                                                      "for his investigations of the physics of the upper atmosphere especially for the discovery of the so-called Appleton layer"
250                                                                                                                                                     "for his development of the Wilson cloud chamber method, and his discoveries therewith in the fields of nuclear physics and cosmic radiation"
261                                                                                                                                                                          "in recognition of his varied and significant writings in which he champions humanitarian ideals and freedom of thought"
266                                                                                                                                                         "for his development of the photographic method of studying nuclear processes and his discoveries regarding mesons made with this method"
272                                                                                                                                                                                       "for their pioneer work on the transmutation of atomic nuclei by artificially accelerated atomic particles"
274                                                                                                                                                                                                                                                 "for their invention of partition chromatography"
275                                                                                                                                                                                                                                                 "for their invention of partition chromatography"
283                                                                                                                                                                   "for his mastery of historical and biographical description as well as for brilliant oratory in defending exalted human values"
304                                                                                                                                                                                                                                   "for their researches into the mechanism of chemical reactions"
311                                                                                                                                                                                                             "for their researches on semiconductors and their discovery of the transistor effect"
320                                                                                                                                                                                                                           "for his work on the structure of proteins, especially that of insulin"
335                                                                                                                                                                                                                                                                                              <NA>
352                                                                                                                                                                                                                                        "for their studies of the structures of globular proteins"
354                                                                                                                                                      "for their discoveries concerning the molecular structure of nucleic acids and its significance for information transfer in living material"
363                                                                                                                                   "for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane"
364                                                                                                                                   "for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane"
394                                                                                                                                                          "for their studies of extremely fast chemical reactions, effected by disturbing the equilibrium by means of very short pulses of energy"
395                                                                                                                                                          "for their studies of extremely fast chemical reactions, effected by disturbing the equilibrium by means of very short pulses of energy"
408                                                                                                                                                                                      "for their contributions to the development of the concept of conformation and its application in chemistry"
436                                                                                                                                                                                                    "for their pioneering contributions to general economic equilibrium theory and welfare theory"
440                                                                                                                                                                                                                           "for their discoveries concerning the chemical structure of antibodies"

In [25]:
fh = df2[['Birth Country', 'Birth Year']]

KeyError: "['Birth Year'] not in index"

In [26]:
print(df2.columns)

Index(['Year', 'Category', 'Prize', 'Motivation', 'Prize Share', 'Laureate ID',
       'Laureate Type', 'Full Name', 'Birth Date', 'Birth City',
       'Birth Country', 'Sex', 'Organization Name', 'Organization City',
       'Organization Country', 'Death Date', 'Death City', 'Death Country'],
      dtype='object')

In [31]:
fh = df2[['Category', 'Prize', 'Death City', 'Birth Country']]
fh

,Category,Prize,Death City,Birth Country
0,Chemistry,The Nobel Prize in Chemistry 1901,Berlin,Netherlands
1,Literature,The Nobel Prize in Literature 1901,Châtenay,France
2,Medicine,The Nobel Prize in Physiology or Medicine 1901,Marburg,Prussia (Poland)
3,Peace,The Nobel Peace Prize 1901,Heiden,Switzerland
4,Peace,The Nobel Peace Prize 1901,Paris,France
...,...,...,...,...
964,Medicine,The Nobel Prize in Physiology or Medicine 2016,NaN,Japan
965,Peace,The Nobel Peace Prize 2016,NaN,Colombia
966,Physics,The Nobel Prize in Physics 2016,NaN,United Kingdom
967,Physics,The Nobel Prize in Physics 2016,NaN,United Kingdom
968,Physics,The Nobel Prize in Physics 2016,NaN,United Kingdom